# Numpy Arrays

* NumPy is a Linear Algebra Library for python, the reason it is so important for Data Science with Python is that almost all the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.
* NumPy is also incredibly fast, as it has bindings to C Libraries.
* NumPy arrays are the main way we will use Numpy throughout the course.
* Numpy arrays essentially come in two flavors: vectors and matrices.
* Vectors are strictly 1-d arrays and matrices are 2-d(but a matrix can have only one row or one column).


## Numpy Arrays from Python List Object

## Title


In [1]:
!pip --version

pip 19.2.1 from c:\users\ihrishi\anaconda3\lib\site-packages\pip (python 3.6)



In [2]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list) #vector 1-d
arr

array([1, 2, 3])

In [3]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat) #matrix 2-d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange() function

In [4]:
np.arange(0,10) #start,stop,step

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## zeros() function

In [8]:
# press shift + tab to get help 

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3,5),dtype=int,order='F')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## ones() function

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## linspace() function returns evenly spaced numbers over the specified intervals

In [14]:
np.linspace(0,5,10) # this will distribute equally from 0 to 5,10 equally 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [16]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

## Identity Matrix

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random samples from the uniform distribution from 0 to 1

In [18]:
np.random.rand(5)

array([0.74435172, 0.46064709, 0.65961241, 0.78937319, 0.65764315])

In [19]:
np.random.rand(5,5)

array([[0.54644598, 0.66173723, 0.4415302 , 0.38089398, 0.00646161],
       [0.93092313, 0.0053153 , 0.89428492, 0.36945337, 0.58861606],
       [0.06076772, 0.76086849, 0.62755191, 0.48517051, 0.39800707],
       [0.88835881, 0.41401098, 0.05833607, 0.22189237, 0.62837768],
       [0.26082749, 0.7473486 , 0.74796486, 0.80714556, 0.07248281]])

## Random sample from the Standard Normal Distribution or Gaussian Distribution (Standard Normal Distribution centred around 0)

In [20]:
np.random.randn(2)

array([-0.87781383,  1.05010445])

In [21]:
np.random.randn(4,4)

array([[-0.97856623, -0.04737045, -0.4452651 , -0.54095502],
       [ 0.6294836 , -0.26735361,  0.61081054, -0.76160689],
       [ 1.80915655,  0.95138895,  0.18171809, -0.35020409],
       [ 1.64373793,  0.29241459, -0.85788606,  0.4012393 ]])

## Random Integers from lower to Higher Number

In [22]:
np.random.randint(1,100) #Lower inclusive, Higher Exclusive

31

In [23]:
np.random.randint(1,100,10)

array([71, 90, 15, 76, 88, 80, 90, 16, 27, 90])

## reshape() Method

In [24]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr.reshape(5,10) # should return an exception

ValueError: cannot reshape array of size 25 into shape (5,10)

## max() and min() 

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr.max()

24

In [31]:
arr.min()

0

## Location of max and min values using argmax() and argmin() Methods

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.argmax()

24

In [34]:
arr.argmin()

0

## Shape Attribute

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arr.shape

(25,)

In [37]:
randarr = np.random.randint(0,50,10).reshape(2,5)

In [38]:
randarr

array([[49,  8,  9,  4, 39],
       [41, 33,  4, 38, 20]])

In [39]:
randarr.shape

(2, 5)

## dtype attribute (datatype)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr.dtype

dtype('int32')

In [42]:
np.zeros(4).dtype

dtype('float64')

In [43]:
np.ones(3).dtype

dtype('float64')

# Numpy Indexing and Selection

In [44]:
arr = np.arange(11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr[8]

8

In [47]:
arr[1:5] # start:stop

array([1, 2, 3, 4])

In [48]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [49]:
arr[:5] #Unbounded Slicing

array([0, 1, 2, 3, 4])

In [50]:
arr[5:] #Unbounded Slicing

array([ 5,  6,  7,  8,  9, 10])

In [51]:
slice_of_arr = arr[0:6] # It's just a reference, it won't create new object in the memory

In [52]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [53]:
slice_of_arr[:] = 99

In [54]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [55]:
arr #It has made the changes in the original array as well

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr_copy = arr.copy() #It will create new object in the memory

In [57]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
arr_copy[:] = 100

In [60]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Numpy Indexing on 2-d array

In [62]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [63]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
arr_2d[0][0]

5

In [65]:
arr_2d[0]

array([ 5, 10, 15])

In [66]:
arr_2d[1][1]

25

In [67]:
arr_2d[1,1]


25

In [68]:
arr_2d[1:,:3]

array([[20, 25, 30],
       [35, 40, 45]])

In [69]:
arr_2d[:,2:]

array([[15],
       [30],
       [45]])

In [70]:
arr_2d[1,2] #More Preferrable

30

In [71]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [72]:
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

## Conditional Selection

In [77]:
arr = np.arange(1,11)

In [78]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
even = arr%2==0
even

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [80]:
arr[even]

array([ 2,  4,  6,  8, 10])

In [81]:
bool_arr = arr > 5

In [82]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [83]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [84]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [85]:
arr[arr<3]

array([1, 2])

In [86]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [87]:
arr_2d[2:,7:]

array([[27, 28, 29],
       [37, 38, 39],
       [47, 48, 49]])

In [88]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Numpy Operations
#### Array with Array
#### Array with Scalars
#### Universal Array Functions

In [89]:
arr = np.arange(11)

In [90]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [92]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [93]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [94]:
arr + 100 #broadcast that scalar to each element in the array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [95]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [96]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [97]:
arr/arr


C:\Users\ihrishi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [99]:
1/0 #invalid operation

ZeroDivisionError: division by zero

In [100]:
arr/0


C:\Users\ihrishi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\ihrishi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [101]:
arr/arr # nan --> null object 0/0

C:\Users\ihrishi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [102]:
1/arr # inf object 1/0

C:\Users\ihrishi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [103]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

### Universal Array Functions

In [104]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [106]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [107]:
np.max(arr)

10

In [108]:
arr.max()

10

In [109]:
np.min(arr)

0

In [110]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [111]:
np.log(arr) # log(0)=-inf

C:\Users\ihrishi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

#### Reference Doc - https://docs.scipy.org/doc/numpy/reference/ufuncs.html

## Exercise

In [112]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [113]:
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [114]:
a=a*5
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [115]:
a=np.arange(10,51)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [116]:
a=np.arange(10,51,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [117]:
np.array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [118]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
np.random.rand(1)


array([0.81896895])

In [120]:
np.random.randn(25)

array([ 0.69283499,  1.51768718,  0.33967213, -0.03367163,  0.9733423 ,
        0.64118088, -0.90411495, -0.19293063,  0.71682252, -0.99149936,
       -1.091752  , -0.11283493,  0.69491659,  1.50530986,  0.52673707,
        0.1474629 ,  0.06314322, -1.72351914,  0.63523079, -1.88941147,
       -0.61723274,  0.49778153, -0.36650152, -0.76341225,  1.5771384 ])

In [121]:
np.arange(0,1,.01,dtype=float).reshape(10,10)#10

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [122]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [123]:
mat = np.arange(1,26).reshape(5,5)

mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [124]:
mat[2:,2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [125]:
mat[3,4]

20

In [126]:
mat[:3,1]

array([ 2,  7, 12])

In [127]:
mat[4]

array([21, 22, 23, 24, 25])

In [128]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [129]:
mat.sum()


325

In [130]:
np.std(mat)


7.211102550927978

In [131]:
mat.sum(axis=0)


array([55, 60, 65, 70, 75])

Reference Doc - https://docs.scipy.org/doc/numpy/reference/ufuncs.html¶